version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # 🔹 Restauration du cache pour accélérer les builds
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # 🔹 Étape 1 : Vérification ESLint
      - run:
          name: Run ESLint
          command: npm run lint

      # 🔹 Étape 2 : Tests unitaires
      - run:
          name: Run tests
          command: npm run test

      # 🔹 Étape 3 : Build de l’application
      - run:
          name: Build project
          command: npm run build

workflows:
  node-tests:
    jobs:
      - build-test
